-- AddColumn planning fields to Activity
ALTER TABLE "Activity"
  ADD COLUMN IF NOT EXISTS quarter TEXT,
  ADD COLUMN IF NOT EXISTS "planStatus" TEXT NOT NULL DEFAULT 'Backlog',
  ADD COLUMN IF NOT EXISTS team TEXT,
  ADD COLUMN IF NOT EXISTS "sizeLabel" TEXT,
  ADD COLUMN IF NOT EXISTS origin TEXT,
  ADD COLUMN IF NOT EXISTS clients TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS "jiraRef" TEXT,
  ADD COLUMN IF NOT EXISTS "planningNote" TEXT;
